[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/mobile"
  to = "/mobile"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404